### ISSUE TITLE
Grading Queue: Can we not refresh the course list every time? This will speed up the reload.

### ISSUE THREAD

**Issue by GeorgeRay** [GeorgeRay/DavisTechCanvasAPIApp#22]
Courses change infrequently but we reload the courses every time we reload the grading queue. Can we create a course list and only refresh it when the form loads and then when the user asks for it.

**Comment by GeorgeRay** [comment]
@cheeseonamonkey This morning, Diana and I upgraded on the Canvas Assistant, and we were not getting all of the assignments. We used the manual course refresh, and all the assignments came in. Can you see if there is logic to only show courses that have assignments on the first load?

**Comment by GeorgeRay** [comment]
I removed the code to look for only courses that had something in the grading queue. But the refresh now is almost as long. Maybe we need a manual course filter button.  Let's talk about this at the next standup.

**Comment by cheeseonamonkey** [comment]
It looks like the initial load is done in the form constructor instead of the load method, I'm not so sure about that:

![image](https://user-images.githubusercontent.com/54555500/106619304-b0424980-652d-11eb-8acc-72f502b29c41.png)

Its also not awaited. But this has been this the case the whole time so I don't think this is the problem.

There are already methods ready for refreshing the course list and refreshing the queue, it sounds like maybe it just needs to refresh the courses at some specific point.

I'm not sure I totally understand the issue though, maybe you can reproduce it on screen for me later.

**Comment by cheeseonamonkey** [comment]
Oh, or is it happening when filtering for a course?

**Comment by GeorgeRay** [comment]
During the course load, there was an if statement that filtered out any course that did not have assignments that needed graded. I removed the if statement and updated the master branch and republished it.  It is a temporary fix, maybe.  We can talk about it at the standup meeting.
________________________________

**Comment by GeorgeRay** [comment]
I think this one is good at the moment.
